---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/rm -rf $DEPLOYPATH/.git* 2>/dev/null || true
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git* 2>/dev/null || true
